# Generated by Django 4.2.4 on 2023-12-03 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookMng', '0011_remove_rating_user_rating_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='average_rating',
            field=models.DecimalField(decimal_places=2, max_digits=3, null=True),
        ),
    ]
